project_id = "sdszjqltoheqhfkeprrd"

[functions.submit-quiz-score]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.fetch-rss-news]
verify_jwt = false

[functions.summarize-article]
verify_jwt = false

[functions.send-critical-alerts]
verify_jwt = false

[functions.submit-form]
verify_jwt = false

[functions.get-subscription]
verify_jwt = false

[functions.update-subscription]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.request-management-link]
verify_jwt = false

[functions.send-digest-emails]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.cleanup-quiz-logs]
verify_jwt = false

[functions.fetch-web3-incidents]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.one-click-unsubscribe]
verify_jwt = false
