project_id = "sdszjqltoheqhfkeprrd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.fetch-rss-news]
verify_jwt = false

[functions.summarize-article]
verify_jwt = false
